'use client'

import { useState, useEffect, useRef } from 'react'

export default function VideosPage() {
  const [videoId, setVideoId] = useState<string | null>(null)
  const [videoUrl, setVideoUrl] = useState<string | null>(null)
  const [status, setStatus] = useState<'idle' | 'generating' | 'polling' | 'done' | 'error'>('idle')
  const [message, setMessage] = useState('')
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const stopPolling = () => {
    if (pollRef.current) clearInterval(pollRef.current)
  }

  useEffect(() => {
    return () => stopPolling()
  }, [])

  const pollStatus = (vid: string) => {
    setStatus('polling')
    setMessage('Video is processing — this takes 2–4 minutes…')
    pollRef.current = setInterval(async () => {
      const res = await fetch(`/api/admin/sba-video-status?video_id=${vid}`)
      const data = await res.json()
      if (data.status === 'completed' && data.video_url) {
        stopPolling()
        setVideoUrl(data.video_url)
        setStatus('done')
        setMessage('Video ready!')
      } else if (data.status === 'failed') {
        stopPolling()
        setStatus('error')
        setMessage('HeyGen reported a failure. Try regenerating.')
      }
    }, 15000)
  }

  const generate = async () => {
    setStatus('generating')
    setMessage('Sending script to HeyGen…')
    setVideoUrl(null)
    try {
      const res = await fetch('/api/admin/generate-sba-video', { method: 'POST' })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      setVideoId(data.video_id)
      pollStatus(data.video_id)
    } catch (e) {
      setStatus('error')
      setMessage(e instanceof Error ? e.message : 'Generation failed')
    }
  }

  return (
    <div className="max-w-3xl">
      <h1 className="text-2xl font-black text-gray-900 mb-2">AI Videos</h1>
      <p className="text-gray-500 mb-8">Generate and manage Maya avatar videos for VortexTrips.</p>

      {/* SBA Opportunity Video */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8 mb-6">
        <div className="flex items-start justify-between mb-4">
          <div>
            <h2 className="text-lg font-bold text-gray-900">SBA Opportunity Video</h2>
            <p className="text-sm text-gray-500 mt-1">
              Maya pitches the earn-with-VortexTrips opportunity. Displayed on the <code className="bg-gray-100 px-1 rounded">/sba</code> page.
            </p>
          </div>
          <span className="text-xs font-semibold px-3 py-1 rounded-full bg-orange-100 text-orange-700">~2 min</span>
        </div>

        {videoUrl ? (
          <div className="mb-6">
            <video
              src={videoUrl}
              controls
              className="w-full rounded-xl bg-black"
              style={{ maxHeight: 360 }}
            />
            <p className="text-xs text-gray-400 mt-2">This video is live on <a href="/sba" target="_blank" className="text-[#FF6B35] underline">/sba</a>.</p>
          </div>
        ) : (
          <div className="bg-gray-50 rounded-xl h-48 flex items-center justify-center mb-6 border border-dashed border-gray-300">
            <p className="text-gray-400 text-sm">No video generated yet</p>
          </div>
        )}

        {message && (
          <div className={`text-sm mb-4 px-4 py-3 rounded-lg ${
            status === 'error' ? 'bg-red-50 text-red-600' :
            status === 'done' ? 'bg-green-50 text-green-700' :
            'bg-blue-50 text-blue-700'
          }`}>
            {status === 'polling' && <span className="mr-2 animate-pulse">⏳</span>}
            {message}
            {videoId && status !== 'done' && (
              <span className="block text-xs mt-1 opacity-70">Video ID: {videoId}</span>
            )}
          </div>
        )}

        <button
          onClick={generate}
          disabled={status === 'generating' || status === 'polling'}
          className="bg-[#FF6B35] text-white font-bold px-6 py-3 rounded-xl hover:bg-orange-600 transition disabled:opacity-50"
        >
          {status === 'generating' ? 'Starting…' :
           status === 'polling' ? 'Processing…' :
           videoUrl ? '🔄 Regenerate Video' : '🎬 Generate SBA Video'}
        </button>
      </div>

      <p className="text-xs text-gray-400">
        Videos are generated by HeyGen using the Maya avatar and Hope voice. Generation typically takes 2–4 minutes.
        Once complete the video URL is saved and displayed automatically on the /sba page.
      </p>
    </div>
  )
}
